### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by ND-451** [RoyalFlyBy/PornHubDownloader#12]
I don't know where else to put this so I'm gonna ask here 
Do you have any plans to make this downloader for Mac or Linux

**Comment by RoyalFlyBy** [comment]
Hi,

I wasn't aware this program was still relevant with PH yeeting it's entire catalogue out of existence... If this program is still relevant I can publish a more up-to-date version later this month.

Linux is already supported `PHDownloader_linux_386` for 32bit & `PHDownloader_linux_amd64` for 64bit, just download and `chmod +x ` whichever you downloaded.

MacOS I don't think I support yet, due to cross platform compilation behind MacOS flavored executables being weird for my codebase. (I can try looking into this again though, I learned some new stuff since the last time I worked on this.)
However as I was typing this I realized that I do have Darwin executables in the repository (`PHDownloader_darwin_amd64` for 64bit, and `PHDownloader_darwin_amd386` for 32bit) so you could try downloading those and executing those from a terminal similar to how the Linux ones would have to be executed.
